### ISSUE TITLE
No CommandLine option "-out" given!

### ISSUE THREAD

**Issue by vzickus** [ChristophKirst/ClearMap#12]
Get this error (in the title) before RuntimeError('alignData: failed executing: ' + cmd) is raised (however, I cannot track the reason down). Any ideas? For some reason, the 

res = os.system(cmd) 

returns res = os.system(cmd)

Traceback:
  File "process_template.py", line 26, in <module>
    resultDirectory  = alignData(**RegistrationAlignmentParameter)

I wonder if this could have anything to do with the "bleed" in atlas. However, I believe I just used the default settings provided in the tutorial, and by eye the atlas and the LSFM data look of similar size.

**Comment by jmmanley** [comment]
Hi,
Christoph should know better, but this error could be caused if you are not giving the proper output path in your alignment parameters. What are you using for `RegistrationAlignmentParameter["resultDirectory"]`?

This error could be due to no path given after the -out flag when it tries to run the Elastix command (lines 455-461 in Alignment/Elastix.py):
`cmd = ElastixBinary + ' -threads 16 -m ' + movingImage + ' -f ' + fixedImage + ' -p ' + affineParameterFile + ' -out ' + resultDirectory`

**Comment by vzickus** [comment]
I can see that the resultsDirectory is successfully created, but empty. I'll have to search for other hard-coded paths that I might have missed in the tutorial. I'll keep you updated.

**Comment by vzickus** [comment]
I could not find any hard-coded bits, and when I print out "RegistrationAlignmentParameter", the paths seem correct. I wonder if it has something with the fact that the bottom of the images look crazy ( https://www.dropbox.com/s/6shi2gubb3uujds/autofluo_for_cfos_resampled-single.tif?dl=0 ) and I have not cropped them...

**Comment by vzickus** [comment]
I tested elastix separately (that is, just elastix on its own from terminal) on the same images, and it worked without issues. For whatever reason, the solution to my problem was to bring the parameter files, as well as the resampled files in the same directory (perhaps there is some intrinsic issue in the way my directories were structured. Closing, and thanks for your help.

**Comment by auesro** [comment]
For future users:
The folders' names, inside the downloaded ClearMap Resources folder, are separated by spaces while the code looks for names in which the spaces have been replaced by underscores "_".
